config/urls.py
"""Django Config APP Urls"""

# Libraries
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

# MDA urls
from .urls_mda import urlpatterns as urlpatterns_mda

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),

    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
] + urlpatterns_mda + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:

pages/urls.py
"""URLS Config of Pages Main"""

# Libraries
from django.urls import path, include

# View
from .views import home_page

app_name = "pages"
urlpatterns = [
    path("", home_page, name="home"),
]

projecttitletest/urls.py
"""All Urls of Projecttitletest"""

# Libraries
from django.urls import path

# Views
from . import views


app_name = "projecttitletests"
urlpatterns = [
    # Steres
    path(
        "steress/",
        views.ListSteresView.as_view(),
        name="steress",
    ),
    path(
        "steress/new/",
        views.SteresCreateView.as_view(),
        name="steres-new",
    ),
    path(
        "steress/<int:pk>/edit/",
        views.SteresUpdateView.as_view(),
        name="steres-edit",
    ),
    path(
        "steress/<int:pk>/delete/",
        views.delete_steres_view,
        name="steres-delete",
    ),

    # User
    path(
        "users/",
        views.ListUserView.as_view(),
        name="users",
    ),
    path(
        "users/new/",
        views.UserCreateView.as_view(),
        name="user-new",
    ),
    path(
        "users/<int:pk>/edit/",
        views.UserUpdateView.as_view(),
        name="user-edit",
    ),
    path(
        "users/<int:pk>/delete/",
        views.delete_user_view,
        name="user-delete",
    ),

    # Preducts
    path(
        "preductss/",
        views.ListPreductsView.as_view(),
        name="preductss",
    ),
    path(
        "preductss/new/",
        views.PreductsCreateView.as_view(),
        name="preducts-new",
    ),
    path(
        "preductss/<int:pk>/edit/",
        views.PreductsUpdateView.as_view(),
        name="preducts-edit",
    ),
    path(
        "preductss/<int:pk>/delete/",
        views.delete_preducts_view,
        name="preducts-delete",
    ),

    # sheppingCart
    path(
        "sheppingcarts/",
        views.ListSheppingcartView.as_view(),
        name="sheppingcarts",
    ),
    path(
        "sheppingcarts/new/",
        views.SheppingcartCreateView.as_view(),
        name="sheppingcart-new",
    ),
    path(
        "sheppingcarts/<int:pk>/edit/",
        views.SheppingcartUpdateView.as_view(),
        name="sheppingcart-edit",
    ),
    path(
        "sheppingcarts/<int:pk>/delete/",
        views.delete_sheppingcart_view,
        name="sheppingcart-delete",
    ),

]

projecttitletest/models/preducts.py
"""Content Preducts"""

# Libraries
from django.db import models

 # Modules


class Preducts(models.Model):
    name = models.CharField("name", null=True, blank=True, max_length=120, )
    description = models.CharField("description", null=True, blank=True, max_length=120, )
    active = models.BooleanField("active", null=True, blank=True, )

    def __str__(self):
        return f"Preducts {self.pk}"

    def __repr__(self):
        return str(self)

projecttitletest/models/sheppingcart.py
"""Content Sheppingcart"""

# Libraries
from django.db import models

 # Modules
from . import user
from . import preducts


class Sheppingcart(models.Model):
    t_name = models.CharField("t_name", null=True, blank=True, max_length=120, )
    user_sc = models.ForeignKey(user.User, on_delete=models.CASCADE)
    preducts_sc = models.ForeignKey(preducts.Preducts, on_delete=models.CASCADE)

    def __str__(self):
        return f"Sheppingcart {self.pk}"

    def __repr__(self):
        return str(self)

projecttitletest/models/steres.py
"""Content Steres"""

# Libraries
from django.db import models

 # Modules
from . import preducts


class Steres(models.Model):
    name = models.CharField("name", null=True, blank=True, max_length=120, )
    description = models.CharField("description", null=True, blank=True, max_length=120, )
    address = models.CharField("address", null=True, blank=True, max_length=120, )
    active = models.BooleanField("active", null=True, blank=True, )
    preducts_sc = models.ForeignKey(preducts.Preducts, on_delete=models.CASCADE)

    def __str__(self):
        return f"Steres {self.pk}"

    def __repr__(self):
        return str(self)

projecttitletest/models/user.py
"""Content User"""

# Libraries
from django.db import models

 # Modules


class User(models.Model):
    name = models.CharField("name", null=True, blank=True, max_length=120, )
    nick = models.CharField("nick", null=True, blank=True, max_length=120, )

    def __str__(self):
        return f"User {self.pk}"

    def __repr__(self):
        return str(self)

projecttitletest/forms.py
"""Forms of Projecttitletest APP"""

# Libraries
from django import forms

# Models
from . import models

class SteresForm(forms.ModelForm):
    """Form to Steres"""
    preducts_sc = forms.ModelChoiceField(queryset=models.preducts.Preducts.objects.all())

    class Meta:
        model = models.steres.Steres
        fields = ["name", "description", "address", "active", "preducts_sc", ]


class UserForm(forms.ModelForm):
    """Form to User"""

    class Meta:
        model = models.user.User
        fields = ["name", "nick", ]


class PreductsForm(forms.ModelForm):
    """Form to Preducts"""

    class Meta:
        model = models.preducts.Preducts
        fields = ["name", "description", "active", ]


class SheppingcartForm(forms.ModelForm):
    """Form to Sheppingcart"""
    user_sc = forms.ModelChoiceField(queryset=models.user.User.objects.all())
    preducts_sc = forms.ModelChoiceField(queryset=models.preducts.Preducts.objects.all())

    class Meta:
        model = models.sheppingcart.Sheppingcart
        fields = ["t_name", "user_sc", "preducts_sc", ]

projecttitletest/views.py
"""Views of Projecttitletest"""

# Libraries
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.conf import settings
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Core
from core.views import FilteredListView

# App Contents
from . import models, filters, forms


# Steres

class ListSteresView(LoginRequiredMixin, FilteredListView):
    template_name = "steres/list.html"
    filterset_class = filters.SteresFilter
    model = models.steres.Steres
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class SteresCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Steres"""
    form_class = forms.SteresForm
    success_url = reverse_lazy("projecttitletests:steress")
    template_name = "steres/new.html"


class SteresUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Steres"""
    form_class = forms.SteresForm
    success_url = reverse_lazy("projecttitletests:steress")
    template_name = "steres/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.steres.Steres, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_steres_view(request, pk):
    steres = get_object_or_404(models.steres.Steres, pk=pk)
    steres.delete()
    return redirect("projecttitletests:steress")


# User

class ListUserView(LoginRequiredMixin, FilteredListView):
    template_name = "user/list.html"
    filterset_class = filters.UserFilter
    model = models.user.User
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class UserCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View User"""
    form_class = forms.UserForm
    success_url = reverse_lazy("projecttitletests:users")
    template_name = "user/new.html"


class UserUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View User"""
    form_class = forms.UserForm
    success_url = reverse_lazy("projecttitletests:users")
    template_name = "user/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.user.User, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_user_view(request, pk):
    user = get_object_or_404(models.user.User, pk=pk)
    user.delete()
    return redirect("projecttitletests:users")


# Preducts

class ListPreductsView(LoginRequiredMixin, FilteredListView):
    template_name = "preducts/list.html"
    filterset_class = filters.PreductsFilter
    model = models.preducts.Preducts
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class PreductsCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Preducts"""
    form_class = forms.PreductsForm
    success_url = reverse_lazy("projecttitletests:preductss")
    template_name = "preducts/new.html"


class PreductsUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Preducts"""
    form_class = forms.PreductsForm
    success_url = reverse_lazy("projecttitletests:preductss")
    template_name = "preducts/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.preducts.Preducts, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_preducts_view(request, pk):
    preducts = get_object_or_404(models.preducts.Preducts, pk=pk)
    preducts.delete()
    return redirect("projecttitletests:preductss")


# Sheppingcart

class ListSheppingcartView(LoginRequiredMixin, FilteredListView):
    template_name = "sheppingcart/list.html"
    filterset_class = filters.SheppingcartFilter
    model = models.sheppingcart.Sheppingcart
    paginate_by = settings.DEFAULT_COUNT_PAGINATE


class SheppingcartCreateView(LoginRequiredMixin, generic.CreateView):
    """Create View Sheppingcart"""
    form_class = forms.SheppingcartForm
    success_url = reverse_lazy("projecttitletests:sheppingcarts")
    template_name = "sheppingcart/new.html"


class SheppingcartUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    """Update View Sheppingcart"""
    form_class = forms.SheppingcartForm
    success_url = reverse_lazy("projecttitletests:sheppingcarts")
    template_name = "sheppingcart/new.html"

    def get_object(self, **kwargs):
        """Return data"""
        return get_object_or_404(models.sheppingcart.Sheppingcart, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        """Modify Context"""
        context = super().get_context_data(**kwargs)
        context["is_update"] = True
        return context


@login_required
def delete_sheppingcart_view(request, pk):
    sheppingcart = get_object_or_404(models.sheppingcart.Sheppingcart, pk=pk)
    sheppingcart.delete()
    return redirect("projecttitletests:sheppingcarts")

projecttitletest/templates/sheppingcart/list.html
{% extends 'content.html' %}{% load static %}{% load page %}

{% block container %}
<div class="title">
    <h3><i class="bi bi-clipboard-plus"></i> List of Sheppingcart</h3>
    <div class="general-actions">
      <a class="btn btn-primary" href="{% url 'projecttitletests:sheppingcart-new' %}">Create</a>
    </div>
  </div>

  <form class="form-filter" method="GET">
    <div class="filters">
{{ filterset.form.as_p }}    </div>
    <input class="btn btn-primary btn-large" type="submit" value="Filter" />
  </form>

  <div class="block">
{% if is_paginated %}      <div class="pagination">
        <p>
Page {{ page_obj.number }} of {{ paginator.num_pages }}        </p>
      </div>
{% endif %}    <div class="block-table">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">T_name</th>
            <th scope="col">User_sc</th>
            <th scope="col">Preducts_sc</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
{% for object in object_list %}          <tr>
              <td>
{{ object.id }}              </td>
              <td>{{ object.t_name }}</td>
              <td><a href="{% url 'projecttitletests:sheppingcart-edit' pk=object.user_sc.pk %}">User {{ object.user_sc.id }}</a></td>
              <td><a href="{% url 'projecttitletests:sheppingcart-edit' pk=object.preducts_sc.pk %}">Preducts {{ object.preducts_sc.id }}</a></td>
              <td>
                <a class="btn btn-secondary btn-small" href="{% url 'projecttitletests:sheppingcart-edit' pk=object.pk %}"><i class="bi bi-pencil-fill"></i></a>
                <a class="btn btn-danger btn-small" href="{% url 'projecttitletests:sheppingcart-delete' pk=object.pk %}"><i class="bi bi-trash-fill"></i></i></a>
              </td>
            </tr>
{% endfor %}        </tbody>
      </table>
    </div>


    {% if is_paginated %}
      <div class="page-buttons">
        {% if page_obj.has_previous %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.previous_page_number %}"><i class="bi bi-chevron-compact-left"></i></a>
        {% endif %}
        {% if page_obj.has_next %}
          <a class="btn btn-secondary" href="?{% param_replace page=page_obj.next_page_number %}"><i class="bi bi-chevron-compact-right"></i></a>
          {% endif %}
      </div>
      {% endif %}
  </div>

  {% endblock container %}

projecttitletest/templates/sheppingcart/new.html
{% extends "content.html" %}
{% load static %}


{% block container %}
  <div class="title">
    <h3>{% if is_update %}<i class="bi bi-pencil-square"></i> Update Sheppingcart {{ object.pk }}{% else %}<i class="bi bi-clipboard-plus"></i> Create New Sheppingcart{% endif %}</h3>
  </div>

  <div class="block">
    <form method="POST" enctype="multipart/form-data">
{% csrf_token %}      <div class="input-field col s12">
        <label for="t_name">{{ form.t_name.label }}</label>
{{ form.t_name }}      </div>
      <div class="input-field col s12">
        <label for="user_sc">{{ form.user_sc.label }}</label>
{{ form.user_sc }}      </div>
      <div class="input-field col s12">
        <label for="preducts_sc">{{ form.preducts_sc.label }}</label>
{{ form.preducts_sc }}      </div>
      <div class="buttons">
        <a class="btn btn-secondary" href="{% if is_update %}{% url 'projecttitletests:sheppingcart-edit' pk=object.pk %}{% else %}{% url 'projecttitletests:sheppingcart-new' %}{% endif %}">Cancel</a>
        <input class="btn btn-primary" type="submit" value="{% if is_update %}Update{% else %}Save{% endif %}">
      </div>
    </form>
  </div>

{% endblock container %}